steps:
  # Build using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cpls-be'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=60'
      - '--port=8080'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--cpu-boost'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=GIN_MODE=release'

substitutions:
  _REGION: 'asia-southeast1'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
