steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cpls-be', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cpls-be']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cpls-be'
      - '--image=gcr.io/$PROJECT_ID/cpls-be'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--port=8080'
      - '--set-env-vars=ENVIRONMENT=production,DB_HOST=${_DB_HOST},DB_PORT=5432,DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME},JWT_SECRET=${_JWT_SECRET}'

substitutions:
  _DB_HOST: 'db.lqmocewqozpyzsknocrc.supabase.co'
  _DB_USER: 'postgres'
  _DB_PASSWORD: ''  # Set via command line: --substitutions=_DB_PASSWORD="your-password"
  _DB_NAME: 'postgres'
  _JWT_SECRET: ''   # Set via command line: --substitutions=_JWT_SECRET="your-secret"

timeout: 900s

# =============================================================================
# DEPLOYMENT INSTRUCTIONS (No Secret Manager required)
# =============================================================================
#
# Option 1: Deploy with substitutions via command line
# -----------------------------------------------------
# gcloud builds submit --config=cloudbuild.yaml \
#   --substitutions=_DB_PASSWORD="your-supabase-password",_JWT_SECRET="your-jwt-secret-32chars"
#
# Option 2: Set variables directly in Cloud Run Console
# -----------------------------------------------------
# 1. Go to: https://console.cloud.google.com/run
# 2. Select service: cpls-be
# 3. Click: EDIT & DEPLOY NEW REVISION
# 4. Tab: VARIABLES & SECRETS
# 5. Add environment variables:
#    - DB_HOST: db.lqmocewqozpyzsknocrc.supabase.co
#    - DB_PORT: 5432
#    - DB_USER: postgres
#    - DB_PASSWORD: your-supabase-password
#    - DB_NAME: postgres
#    - JWT_SECRET: your-jwt-secret-32chars
#    - ENVIRONMENT: production
#
# Option 3: Update existing service via gcloud CLI
# -------------------------------------------------
# gcloud run services update cpls-be \
#   --region=asia-southeast1 \
#   --set-env-vars="DB_HOST=db.lqmocewqozpyzsknocrc.supabase.co" \
#   --set-env-vars="DB_PORT=5432" \
#   --set-env-vars="DB_USER=postgres" \
#   --set-env-vars="DB_PASSWORD=your-supabase-password" \
#   --set-env-vars="DB_NAME=postgres" \
#   --set-env-vars="JWT_SECRET=your-jwt-secret-32chars" \
#   --set-env-vars="ENVIRONMENT=production"
#
# =============================================================================
