steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-backend', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'go-backend', '--image', 'gcr.io/$PROJECT_ID/go-backend', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']