steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cpls-be', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cpls-be']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cpls-be'
      - '--image=gcr.io/$PROJECT_ID/cpls-be'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--timeout=600s'
      - '--port=8080'
      # Environment variables (will be set from substitutions)
      - '--set-env-vars=DB_HOST=${_DB_HOST}'
      - '--set-env-vars=DB_PORT=${_DB_PORT}'
      - '--set-env-vars=DB_USER=${_DB_USER}'
      - '--set-env-vars=DB_PASSWORD=${_DB_PASSWORD}'
      - '--set-env-vars=DB_NAME=${_DB_NAME}'
      - '--set-env-vars=JWT_SECRET=${_JWT_SECRET}'
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT}'

# Substitutions for environment variables
# Override these when running: gcloud builds submit --substitutions=_DB_PASSWORD=xxx,...
substitutions:
  _DB_HOST: 'db.lqmocewqozpyzsknocrc.supabase.co'
  _DB_PORT: '5432'
  _DB_USER: 'postgres'
  _DB_PASSWORD: 'REPLACE_WITH_YOUR_SUPABASE_PASSWORD'  # MUST be overridden
  _DB_NAME: 'postgres'
  _JWT_SECRET: 'REPLACE_WITH_JWT_SECRET'  # Generate with: openssl rand -base64 32
  _ENVIRONMENT: 'production'

timeout: 1200s  # 20 minutes for build + deploy
