steps:
  # Build Docker image using Dockerfile (includes templates)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cpls-be'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # Resource allocation
      - '--memory=1Gi'
      - '--cpu=2'
      - '--timeout=60'
      - '--port=8080'
      # Concurrency and scaling
      - '--concurrency=100'
      - '--max-instances=10'
      - '--min-instances=0'
      # Startup probe - give more time to start
      - '--cpu-boost'
      # Environment variables
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=GIN_MODE=release'
      # PostgreSQL (Supabase)
      - '--set-env-vars=DB_HOST=${_DB_HOST}'
      - '--set-env-vars=DB_PORT=5432'
      - '--set-env-vars=DB_USER=postgres'
      - '--set-env-vars=DB_PASSWORD=${_DB_PASSWORD}'
      - '--set-env-vars=DB_NAME=postgres'
      # MongoDB Atlas
      - '--set-env-vars=MONGODB_URI=${_MONGODB_URI}'
      - '--set-env-vars=MONGODB_DATABASE=${_MONGODB_DATABASE}'
      # JWT
      - '--set-env-vars=JWT_SECRET=${_JWT_SECRET}'
      # CORS
      - '--set-env-vars=CORS_ORIGINS=${_CORS_ORIGINS}'
      - '--set-env-vars=REQUIRE_API_AUTH=false'

substitutions:
  _REGION: 'asia-southeast1'
  _DB_HOST: 'CONFIGURE_IN_CLOUD_BUILD_TRIGGER'
  _DB_PASSWORD: 'CONFIGURE_IN_CLOUD_BUILD_TRIGGER'
  _JWT_SECRET: 'CONFIGURE_IN_CLOUD_BUILD_TRIGGER'
  _MONGODB_URI: 'CONFIGURE_IN_CLOUD_BUILD_TRIGGER'
  _MONGODB_DATABASE: 'cpls_stock'
  _CORS_ORIGINS: 'http://localhost:3000'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cpls/cpls-be:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
